#!/bin/sh

# based on https://github.com/thoughtbot/laptop script

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

dotfiles_root=$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)

fancy_echo() {
  local fmt="$1"; shift
  printf "\n$fmt\n" "$@"
}

brew_install_or_upgrade() {
  if brew_is_installed "$1"; then
    if brew_is_upgradable "$1"; then
      fancy_echo "Upgrading %s..." "$1"
      brew upgrade "$@"
    else
      fancy_echo "Already using the latest version of %s. Skipping..." "$1"
    fi
  else
    fancy_echo "Installing %s..." "$1"
    brew install "$@"
  fi
}

brew_is_installed() {
  local name="$(brew_expand_alias "$1")"
  brew list -1 | grep -Fqx "$name"
}

brew_is_upgradable() {
  local name="$(brew_expand_alias "$1")"
  ! brew outdated --quiet "$name" >/dev/null
}

brew_tap() {
  brew tap "$1" 2> /dev/null
}

brew_expand_alias() {
  brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

brew_service_restart() {
  fancy_echo "Restarting %s..." "$1"
  brew services restart "$@" 2>/dev/null
}

download_font(){
  local font_url=$1
  local font_name=$(basename "$font_url" | sed "s/%20/ /g")

  if [ ! -f "$HOME/Library/Fonts/${font_name}" ]; then
    fancy_echo "Downloading $font_name font..."
    wget "$font_url" -q -O "$HOME/Library/Fonts/$font_name"
  else
    fancy_echo "Font $font_name is already installed. Skipping..."
  fi
}

if ! command -v brew > /dev/null; then
  fancy_echo "Installing Homebrew..."
  curl -fsS "https://raw.githubusercontent.com/Homebrew/install/master/install.sh" | /bin/bash
  export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping..."
fi

fancy_echo "Updating Homebrew formulas..."
brew update

brew_install_or_upgrade "fish"
brew_install_or_upgrade "git"
brew_install_or_upgrade "postgresql@14"
brew_service_restart "postgresql@14"
brew_install_or_upgrade "the_silver_searcher"
brew_install_or_upgrade "vim"
brew_install_or_upgrade "vimpager"
brew_install_or_upgrade "ctags"
brew_install_or_upgrade "tmux"
brew_install_or_upgrade "reattach-to-user-namespace"
brew_install_or_upgrade "imagemagick"
brew_install_or_upgrade "wget"
brew_install_or_upgrade "fortune"
brew_install_or_upgrade "python"
brew_install_or_upgrade "pyenv"
brew_install_or_upgrade "pyenv-virtualenv"
brew_install_or_upgrade "openssl"
brew_install_or_upgrade "libyaml"
brew_install_or_upgrade "apache-spark"
brew_install_or_upgrade "exercism"
brew_install_or_upgrade "lynx"
brew_install_or_upgrade "pandoc"
brew_install_or_upgrade "java"

download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Black%20for%20Powerline.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Bold%20for%20Powerline.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20ExtraLight%20for%20Powerline.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Light%20for%20Powerline.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Medium%20for%20Powerline.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Powerline%20BlackItalic.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Powerline%20BoldItalic.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Powerline%20ExtraLightItalic.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Powerline%20Italic.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Powerline%20LightItalic.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Powerline%20MediumItalic.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Powerline%20SemiboldItalic.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20Semibold%20for%20Powerline.otf"
download_font "https://github.com/powerline/fonts/raw/fe396ef6f6b9b315f30af7d7229ff21f67a66e12/SourceCodePro/Source%20Code%20Pro%20for%20Powerline.otf"

fancy_echo "Fetching git submodules..."
cd $dotfiles_root
git submodule update --init --recursive

fancy_echo "Installing python versions..."
pyenv install -s 2.7.18
pyenv install -s 3.9.13
fancy_echo "Setting global python verions..."
pyenv global 3.9.13 2.7.18
